version: '3.1'

services:
  metrics_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: dev_only
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
